export const GET_ITEMS = 'GET_ITEMS'
export const INCREMENTAR = 'INCREMENTAR'
export const RESTAR = 'RESTAR'
export const LIMPIAR_ITEMS = 'LIMPIAR_ITEMS'
export const SELECT = 'SELECT'
export const ESPACIO = 'ESPACIO'
export const DESCUENTO = 'DESCUENTO'
export const TOTAL = 'TOTAL'